site_name: Веб-терминал
nav:
  - 'Терминал':
      - 'Предложения и вопросы': '1.md'
  - 'Общее':
      - 'Верхняя панель': '/topbar/topbar.md'
      - 'Нижняя панель': '/bottombar/bottombar.md'
      - 'Вкладки в терминале': '/tabs/tabs.md'
      - 'Виджеты': 'widgets.md'
  - 'Виджеты':
      - 'График': '1.md'
      - 'Индикаторы': '1.md'
      - 'Устаревший график': '1.md'
      - 'Заявка': 'Orders.md'
      - 'Активные заявки': '1.md'
      - 'Портфель': '1.md'
      - 'Подписки': '1.md'
      - 'Об инструменте': '1.md'
      - 'Инструменты': '1.md'
      - 'Операции': '1.md'
      - 'Стакан': '/orderbook/index.md'
      - 'Скринер': '1.md'
      - 'Маржинальная торговля': '1.md'
      - 'Лента': '1.md'
      - 'Календарь инвестора': '1.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    
