site_name: Веб-терминал
nav:
  - 'Терминал':
      - 'Общее': 'intro/intro.md'
      - 'Верхняя панель': 'topbar/topbar.md'
      - 'Нижняя панель': 'bottombar/bottombar.md'
      - 'Вкладки в терминале': 'tabs/tabs.md'
      - 'Виджеты': 'widgets/widgets.md'
  - 'Виджеты':
      - 'Заявка': 'orders/orders1.md'
      - 'Активные заявки': 'active_orders/active_orders.md'
      - 'Скринер': 'screener/screener.md'
      - 'Инструменты': 'instruments/instruments.md'
      - 'Календарь дивидендов': 'calendar/calendar.md'
      - 'График': 'tv_chart/tv_chart.md'
      - 'Устаревший график': 'old_chart/old_chart.md'
      - 'Стакан': 'orderbook/index.md'
      - 'Об инструменте': 'about/about.md'
      - 'Портфель': 'portfolio/portfolio.md'
      - 'Пополнение/Вывод': 'in_out/in_out.md'
      - 'Операции': 'transactions/transactions.md'
      - 'Маржинальная торговля': 'margin/margin.md'
      - 'Подписки': 'alarm/alarm.md'
      - 'Лента': 'feed/feed.md'   
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    
