site_name: Веб-терминал
nav:
  - 'Терминал':
      - 'Общее': '/intro/intro.md'
      - 'Верхняя панель': '/topbar/topbar.md'
      - 'Нижняя панель': '/bottombar/bottombar.md'
      - 'Вкладки в терминале': '/tabs/tabs.md'
      - 'Виджеты': '/widgets/widgets.md'
  - 'Виджеты':
      - 'График': '/tv_chart/tv_chart.md'
      - 'Индикаторы': '/tv_chart/indicators/indicators.md'
      - 'Устаревший график': '/old_chart/old_chart.md'
      - 'Заявка': '/orders/orders1.md'
      - 'Активные заявки': '/orders/active.md'
      - 'Портфель': '/portfolio/portfolio.md'
      - 'Подписки': '/alarm/alarm.md'
      - 'Об инструменте': '/about/about.md'
      - 'Инструменты': '/instruments/instruments.md'
      - 'Операции': '/transactions/transactions.md'
      - 'Стакан': '/orderbook/index.md'
      - 'Скринер': '/screener/screener.md'
      - 'Маржинальная торговля': '/margin/margin.md'
      - 'Лента': '/feed/feed.md'
      - 'Календарь инвестора': '/calendar/calendar.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    
